name:                pfile
version:             0.1.0.0
github:              "illia-shkroba/pfile"
license:             BSD-3-Clause
author:              "Illia Shkroba"
maintainer:          "is@pjwstk.edu.pl"
copyright:           "2024 Illia Shkroba"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/illia-shkroba/pfile#readme>

default-extensions:
- NoImplicitPrelude

dependencies:
- base >= 4.7 && < 5
- HUnit
- aeson
- aeson-pretty
- directory
- filepath
- mtl
- optparse-applicative
- protolude
- temporary
- transformers
- unordered-containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  pfile:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pfile

tests:
  pfile-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pfile
    - hspec
    - tasty
    - tasty-hspec
    - tasty-quickcheck
