name:                pfile
version:             0.1.0.1
github:              "illia-shkroba/pfile"
license:             BSD-3-Clause
author:              "Illia Shkroba"
maintainer:          "is@pjwstk.edu.pl"
copyright:           "2024 Illia Shkroba"
category:            Filesystem
synopsis:            CLI program for profiles management.

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/illia-shkroba/pfile#readme>

default-extensions:
- NoImplicitPrelude

dependencies:
- base >= 4.7 && < 5
- aeson >= 2.1.2 && <= 2.2.3.0
- aeson-pretty >= 0.8.9 && < 0.9
- directory >= 1.3.7 && < 1.4
- filepath >= 1.4.2 && < 1.5
- mtl >= 2.2.2 && <= 2.3.1
- optparse-applicative >= 0.17.1 && <= 0.18.1.0
- protolude >= 0.3.3 && < 0.4
- temporary >= 1.3 && < 1.4
- transformers >= 0.5.6 && <= 0.6.1.0
- unordered-containers >= 0.2.19 && < 0.3

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  pfile:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pfile

tests:
  pfile-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pfile
    - HUnit >= 1.6.2 && < 1.7
    - hspec >= 2.10.10 && <= 2.11.9
    - tasty >= 1.4.3 && <= 1.5
    - tasty-hspec >= 1.2.0.3 && < 1.3
    - tasty-quickcheck >= 0.10.2 && <= 0.11
